<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Shivanagayya" failures="1" tests="2" name="Error Validation Test" time="17.542" errors="0" timestamp="18 Aug 2023 11:34:26 GMT">
  <testcase classname="testPrograms.ErrorValidationsTest" name="LoginApplication" time="1.263">
    <skipped/>
  </testcase> <!-- LoginApplication -->
  <testcase classname="testPrograms.ErrorValidationsTest" name="LoginApplication" time="1.203">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testPrograms.ErrorValidationsTest.LoginApplication(ErrorValidationsTest.java:21)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- LoginApplication -->
</testsuite> <!-- Error Validation Test -->
