<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="3" failed="1" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-08-23T18:13:11Z" name="Suite" finished-at="2023-08-23T18:15:08Z" duration-ms="117285">
    <groups>
      <group name="purchaseOrder">
        <method signature="SubmitOrderTest.submiteOrder(java.util.HashMap)[pri:0, instance:testPrograms.SubmitOrderTest@3daf7722]" name="submiteOrder" class="testPrograms.SubmitOrderTest"/>
      </group> <!-- purchaseOrder -->
      <group name="ErrorHandlingTest">
        <method signature="ErrorValidationsTest.LoginApplication()[pri:0, instance:testPrograms.ErrorValidationsTest@5f354bcf]" name="LoginApplication" class="testPrograms.ErrorValidationsTest"/>
      </group> <!-- ErrorHandlingTest -->
    </groups>
    <test started-at="2023-08-23T18:13:11Z" name="Test" finished-at="2023-08-23T18:15:08Z" duration-ms="117285">
      <class name="testPrograms.ErrorValidationsTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:testPrograms.ErrorValidationsTest@5f354bcf]" started-at="2023-08-23T18:13:11Z" name="launchApplication" finished-at="2023-08-23T18:13:25Z" duration-ms="13562" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="LoginApplication()[pri:0, instance:testPrograms.ErrorValidationsTest@5f354bcf]" started-at="2023-08-23T18:13:25Z" name="LoginApplication" finished-at="2023-08-23T18:13:26Z" duration-ms="1086" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.assertNotEquals(Assert.java:1157)
at org.testng.Assert.assertNotEquals(Assert.java:1162)
at testPrograms.ErrorValidationsTest.LoginApplication(ErrorValidationsTest.java:21)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginApplication -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testPrograms.ErrorValidationsTest@5f354bcf]" started-at="2023-08-23T18:13:26Z" name="tearDown" finished-at="2023-08-23T18:13:26Z" duration-ms="135" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:testPrograms.ErrorValidationsTest@5f354bcf]" started-at="2023-08-23T18:13:26Z" name="launchApplication" finished-at="2023-08-23T18:13:31Z" duration-ms="5198" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="LoginApplication()[pri:0, instance:testPrograms.ErrorValidationsTest@5f354bcf]" started-at="2023-08-23T18:13:31Z" name="LoginApplication" finished-at="2023-08-23T18:13:32Z" duration-ms="730" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.assertNotEquals(Assert.java:1157)
at org.testng.Assert.assertNotEquals(Assert.java:1162)
at testPrograms.ErrorValidationsTest.LoginApplication(ErrorValidationsTest.java:21)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginApplication -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testPrograms.ErrorValidationsTest@5f354bcf]" started-at="2023-08-23T18:13:32Z" name="tearDown" finished-at="2023-08-23T18:13:32Z" duration-ms="133" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testPrograms.ErrorValidationsTest -->
      <class name="testPrograms.SubmitOrderTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:testPrograms.SubmitOrderTest@3daf7722]" started-at="2023-08-23T18:13:32Z" name="launchApplication" finished-at="2023-08-23T18:13:38Z" duration-ms="5340" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submiteOrder(java.util.HashMap)[pri:0, instance:testPrograms.SubmitOrderTest@3daf7722]" started-at="2023-08-23T18:13:38Z" name="submiteOrder" data-provider="getData" finished-at="2023-08-23T18:14:40Z" duration-ms="62329" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Sbg@2023, product=ZARA COAT 3, email=shiva.swami88@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submiteOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testPrograms.SubmitOrderTest@3daf7722]" started-at="2023-08-23T18:14:40Z" name="tearDown" finished-at="2023-08-23T18:14:40Z" duration-ms="86" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:testPrograms.SubmitOrderTest@3daf7722]" started-at="2023-08-23T18:14:40Z" name="launchApplication" finished-at="2023-08-23T18:14:45Z" duration-ms="4698" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submiteOrder(java.util.HashMap)[pri:0, instance:testPrograms.SubmitOrderTest@3daf7722]" started-at="2023-08-23T18:14:45Z" name="submiteOrder" data-provider="getData" finished-at="2023-08-23T18:15:01Z" duration-ms="16326" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Sbg@2023, product=ADIDAS ORIGINAL, email=shiva.swami88@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submiteOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testPrograms.SubmitOrderTest@3daf7722]" started-at="2023-08-23T18:15:01Z" name="tearDown" finished-at="2023-08-23T18:15:01Z" duration-ms="135" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:testPrograms.SubmitOrderTest@3daf7722]" started-at="2023-08-23T18:15:01Z" name="launchApplication" finished-at="2023-08-23T18:15:07Z" duration-ms="5324" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="orderHistoryTest()[pri:0, instance:testPrograms.SubmitOrderTest@3daf7722]" started-at="2023-08-23T18:15:07Z" name="orderHistoryTest" finished-at="2023-08-23T18:15:08Z" depends-on-methods="testPrograms.SubmitOrderTest.submiteOrder" duration-ms="1618" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- orderHistoryTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testPrograms.SubmitOrderTest@3daf7722]" started-at="2023-08-23T18:15:08Z" name="tearDown" finished-at="2023-08-23T18:15:08Z" duration-ms="172" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testPrograms.SubmitOrderTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
